### ISSUE TITLE
Interface para Gerar Clusters

### ISSUE THREAD

**Issue by lucasvenez** [lucasvenez/tonerscheduling#4]
@stould,

Você criou a interface `Clusterable` com o método `getClusters`. A implementação dessa interface na classe `PaintGraphCluster` permite que um `BitSet` seja recebido por meio do método construtor.

No entanto, percebi que o resultado do método supracita é um `List<BitSet`. No que tange o modelo, os clusters não seriam representados por meio de um `List<List<BitSet>`. Um vetor poderia ser representado por um único `BitSet`, mas percebi que não fez assim no método que carrega os dados na classe `DataLoader`.

Esta certa essas afirmações? Por gentileza, me ajude a entender melhor ou a corrigir essa interface.

[]'s

**Comment by stould** [comment]
Então, o intuíto dessa classe é gerar grupos de receitas tamanho no máximo _clusterSize_., então acho que é interessante a interface esperar uma Lista<?> como retorno.Caso eu esteja errado, como seriam representados os clusters, senão por meio de blocos de receitas?

**Comment by stould** [comment]
Se você achar que eu to fazendo errado a ideia de orientação de objetos, me diga o que eu preciso mudar, que eu mudo, beleza? Ou pode mudar você msm se quiser.

**Comment by lucasvenez** [comment]
É uma dúvida mesmo. Do jeito que eu pensei, é exatamente esse o retorno, só que deveria ser um `List<List<BitSet>>`, pois cada cluster, possuirá um conjunto de requisções. Pelo o que eu entendi, se a gente modelar com `List<BitSet>`, é como se cada cluster tivesse somente um pedido. Estou pensando como você?

**Comment by stould** [comment]
Exatamente, eu pensei em deixar com List<?> pq não sabia exatamente se sempre seria uma List<List<BitSet>>, então deixei genérico, mas se quiser pode deixar fixo List<List<Bistset>>. 👍

**Comment by stould** [comment]
Mas na vdd, um cluster tem no máximo _clusterSize_ de receitas dentro. Eu basicamente pego as receitas e divido elas em blocos, só isso. Porém a junção delas é feito de um jeito que eu acho que vai nos ajudar bastante.

**Comment by lucasvenez** [comment]
@stould, me desculpe. Eu que vi errado. Já está implementado exatamente do jeito que eu questionei você. Vlw! Abraços!

**Comment by stould** [comment]
Beleza, se precisa de alguma informação de como usar me pergunta. Na classe Main eu criei meio errado, eu não usei a interface. Acho que o correto seria: `Clusterable pgc = new PaintGraphCluster(recipes, m);`. Valeu!
